--- #YAML:1.0
 name: Lyrics-Fetcher
 abstract: Perl extension to fetch song lyrics
 version: 0.5.1
 author:
   - David Precious <davidp@preshweb.co.uk>
 license: perl
 distribution_type: module
 requires:
   perl: 5.005
 build_requires:
   Test::More: 0
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: hand
